// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot'

export const vMainOrderStatus = v.picklist([
  'New',
  'Bill',
  'Closed',
  'Banquet',
])

export const vMainOrder = v.object({
  end_time: v.optional(v.string()),
  id: v.optional(v.string()),
  start_time: v.optional(v.string()),
  status: v.optional(vMainOrderStatus),
})

export const vMainReservationStatus = v.picklist([
  'Живая очередь',
  'Новая',
  'Заявка',
  'Открыт',
  'Закрыт',
])

export const vMainReservation = v.object({
  end_time: v.optional(v.string()),
  id: v.optional(v.pipe(v.number(), v.integer())),
  name_for_reservation: v.optional(v.string()),
  num_people: v.optional(v.pipe(v.number(), v.integer())),
  phone_number: v.optional(v.string()),
  seating_time: v.optional(v.string()),
  status: v.optional(vMainReservationStatus),
})

export const vMainRestaurant = v.object({
  closing_time: v.optional(v.string()),
  id: v.optional(v.pipe(v.number(), v.integer())),
  opening_time: v.optional(v.string()),
  restaurant_name: v.optional(v.string()),
  timezone: v.optional(v.string()),
})

export const vMainZone = v.picklist([
  '1 этаж',
  '2 этаж',
  'Банкетный зал',
])

export const vMainTable = v.object({
  capacity: v.optional(v.pipe(v.number(), v.integer())),
  id: v.optional(v.string()),
  number: v.optional(v.string()),
  orders: v.optional(v.array(vMainOrder)),
  reservations: v.optional(v.array(vMainReservation)),
  zone: v.optional(vMainZone),
})

export const vMainBookingResponse = v.object({
  available_days: v.optional(v.array(v.string())),
  current_day: v.optional(v.string()),
  restaurant: v.optional(vMainRestaurant),
  tables: v.optional(v.array(vMainTable)),
})

/**
 * OK
 */
export const vGetApiBookingResponse = vMainBookingResponse
